import React from "react";
import "./App.css";

export const App = (): React.ReactElement => {
  return (
    <table className="centered">
      <thead>
        <tr>
          <th>Type</th>
          <th>Spirit Box</th>
          <th>Fingerprints</th>
          <th>Book writing</th>
          <th>Ghost Orbs</th>
          <th>EMF 5</th>
          <th>Freezing</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Spirit</td>
          <td>X</td>
          <td>X</td>
          <td>X</td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>Wraith</td>
          <td>X</td>
          <td>X</td>
          <td></td>
          <td></td>
          <td></td>
          <td>X</td>
        </tr>
        <tr>
          <td>Phantom</td>
          <td></td>
          <td></td>
          <td></td>
          <td>X</td>
          <td>X</td>
          <td>X</td>
        </tr>
        <tr>
          <td>Poltergeist</td>
          <td>X</td>
          <td>X</td>
          <td></td>
          <td>X</td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>Banshee</td>
          <td></td>
          <td>X</td>
          <td></td>
          <td></td>
          <td>X</td>
          <td>X</td>
        </tr>
        <tr>
          <td>Jinn</td>
          <td>X</td>
          <td></td>
          <td></td>
          <td>X</td>
          <td>X</td>
          <td></td>
        </tr>
        <tr>
          <td>Mare</td>
          <td>X</td>
          <td></td>
          <td></td>
          <td>X</td>
          <td></td>
          <td>X</td>
        </tr>
        <tr>
          <td>Revenant</td>
          <td></td>
          <td>X</td>
          <td>X</td>
          <td></td>
          <td>X</td>
          <td></td>
        </tr>
        <tr>
          <td>Shade</td>
          <td></td>
          <td></td>
          <td>X</td>
          <td>X</td>
          <td>X</td>
          <td></td>
        </tr>
        <tr>
          <td>Demon</td>
          <td>X</td>
          <td></td>
          <td>X</td>
          <td></td>
          <td></td>
          <td>X</td>
        </tr>
        <tr>
          <td>Yurei</td>
          <td></td>
          <td></td>
          <td>X</td>
          <td>X</td>
          <td></td>
          <td>X</td>
        </tr>
        <tr>
          <td>Oni</td>
          <td>X</td>
          <td></td>
          <td>X</td>
          <td></td>
          <td>X</td>
          <td></td>
        </tr>
      </tbody>
    </table>
  );
};
